behaviors:
  Shooting:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      beta: 0.1
    network_settings:
      hidden_units: 128
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 128
    max_steps: 5.0e5
    time_horizon: 128
    summary_freq: 10000